# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7519948b032b6e30ece3b3fd09624474cde85ee9021117e1bb03348400f20a06b8c8a2be28d55e63a7616d0c88444ea23c6ad7a8f02362ded9e63526e891a76

test:
  secret_key_base: 9a3e4a0af95529b85b282c85f82ba94a11b27ed5df88115837c0ce455d7a6f73bfc78fac3e710bf5a42fb02b5307308cefc195977c80646a2820e936b5eb088f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
